// <auto-generated />
using System;
using JetGo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JetGo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JetGoDbContext))]
    [Migration("20260427101518_AddNotificationsAndNews")]
    partial class AddNotificationsAndNews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JetGo.Domain.Entities.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Airlines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "OU",
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Croatia Airlines"
                        },
                        new
                        {
                            Id = 2,
                            Code = "OS",
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Austrian Airlines"
                        },
                        new
                        {
                            Id = 3,
                            Code = "JU",
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Air Serbia"
                        },
                        new
                        {
                            Id = 4,
                            Code = "TK",
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Turkish Airlines"
                        },
                        new
                        {
                            Id = 5,
                            Code = "LH",
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Lufthansa"
                        });
                });

            modelBuilder.Entity("JetGo.Domain.Entities.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("IataCode")
                        .IsUnique();

                    b.ToTable("Airports", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            IataCode = "SJJ",
                            Latitude = 43.8246m,
                            Longitude = 18.3315m,
                            Name = "Sarajevo International Airport"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            IataCode = "OMO",
                            Latitude = 43.2829m,
                            Longitude = 17.8459m,
                            Name = "Mostar International Airport"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            IataCode = "BNX",
                            Latitude = 44.9414m,
                            Longitude = 17.2975m,
                            Name = "Banja Luka International Airport"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            IataCode = "ZAG",
                            Latitude = 45.7429m,
                            Longitude = 16.0688m,
                            Name = "Zagreb Franjo Tudman Airport"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 5,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            IataCode = "VIE",
                            Latitude = 48.1103m,
                            Longitude = 16.5697m,
                            Name = "Vienna International Airport"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 6,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            IataCode = "BEG",
                            Latitude = 44.8184m,
                            Longitude = 20.3091m,
                            Name = "Belgrade Nikola Tesla Airport"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 7,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            IataCode = "IST",
                            Latitude = 41.2753m,
                            Longitude = 28.7519m,
                            Name = "Istanbul Airport"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 8,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            IataCode = "FRA",
                            Latitude = 50.0379m,
                            Longitude = 8.5622m,
                            Name = "Frankfurt Airport"
                        });
                });

            modelBuilder.Entity("JetGo.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId", "Name")
                        .IsUnique();

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sarajevo"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Mostar"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Banja Luka"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Zagreb"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 3,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bec"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 4,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Beograd"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 5,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Istanbul"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 6,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Frankfurt"
                        });
                });

            modelBuilder.Entity("JetGo.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsoCode")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsoCode = "BA",
                            Name = "Bosna i Hercegovina"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsoCode = "HR",
                            Name = "Hrvatska"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsoCode = "AT",
                            Name = "Austrija"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsoCode = "RS",
                            Name = "Srbija"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsoCode = "TR",
                            Name = "Turska"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsoCode = "DE",
                            Name = "Njemacka"
                        });
                });

            modelBuilder.Entity("JetGo.Domain.Entities.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArrivalAirportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartureAirportId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RouteCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalAirportId");

                    b.HasIndex("DepartureAirportId");

                    b.HasIndex("RouteCode")
                        .IsUnique();

                    b.ToTable("Destinations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Destinations_DifferentAirports", "[DepartureAirportId] <> [ArrivalAirportId]");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalAirportId = 4,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            DepartureAirportId = 1,
                            IsActive = true,
                            RouteCode = "SJJ-ZAG"
                        },
                        new
                        {
                            Id = 2,
                            ArrivalAirportId = 5,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            DepartureAirportId = 1,
                            IsActive = true,
                            RouteCode = "SJJ-VIE"
                        },
                        new
                        {
                            Id = 3,
                            ArrivalAirportId = 6,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            DepartureAirportId = 3,
                            IsActive = true,
                            RouteCode = "BNX-BEG"
                        },
                        new
                        {
                            Id = 4,
                            ArrivalAirportId = 7,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            DepartureAirportId = 2,
                            IsActive = true,
                            RouteCode = "OMO-IST"
                        },
                        new
                        {
                            Id = 5,
                            ArrivalAirportId = 8,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            DepartureAirportId = 1,
                            IsActive = true,
                            RouteCode = "SJJ-FRA"
                        },
                        new
                        {
                            Id = 6,
                            ArrivalAirportId = 5,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            DepartureAirportId = 3,
                            IsActive = true,
                            RouteCode = "BNX-VIE"
                        });
                });

            modelBuilder.Entity("JetGo.Domain.Entities.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrivalAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("FlightNumber")
                        .IsUnique();

                    b.ToTable("Flights", null, t =>
                        {
                            t.HasCheckConstraint("CK_Flights_ArrivalAfterDeparture", "[ArrivalAtUtc] > [DepartureAtUtc]");

                            t.HasCheckConstraint("CK_Flights_SeatsPositive", "[TotalSeats] >= 0 AND [AvailableSeats] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirlineId = 1,
                            ArrivalAtUtc = new DateTime(2026, 5, 10, 9, 10, 0, 0, DateTimeKind.Utc),
                            AvailableSeats = 6,
                            BasePrice = 129.00m,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            DepartureAtUtc = new DateTime(2026, 5, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            DestinationId = 1,
                            FlightNumber = "JG100",
                            Status = 1,
                            TotalSeats = 6
                        },
                        new
                        {
                            Id = 2,
                            AirlineId = 2,
                            ArrivalAtUtc = new DateTime(2026, 5, 10, 13, 55, 0, 0, DateTimeKind.Utc),
                            AvailableSeats = 6,
                            BasePrice = 149.00m,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            DepartureAtUtc = new DateTime(2026, 5, 10, 12, 30, 0, 0, DateTimeKind.Utc),
                            DestinationId = 2,
                            FlightNumber = "JG101",
                            Status = 1,
                            TotalSeats = 6
                        },
                        new
                        {
                            Id = 3,
                            AirlineId = 3,
                            ArrivalAtUtc = new DateTime(2026, 5, 11, 8, 50, 0, 0, DateTimeKind.Utc),
                            AvailableSeats = 6,
                            BasePrice = 99.00m,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            DepartureAtUtc = new DateTime(2026, 5, 11, 7, 45, 0, 0, DateTimeKind.Utc),
                            DestinationId = 3,
                            FlightNumber = "JG102",
                            Status = 1,
                            TotalSeats = 6
                        },
                        new
                        {
                            Id = 4,
                            AirlineId = 4,
                            ArrivalAtUtc = new DateTime(2026, 5, 11, 17, 50, 0, 0, DateTimeKind.Utc),
                            AvailableSeats = 6,
                            BasePrice = 179.00m,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            DepartureAtUtc = new DateTime(2026, 5, 11, 15, 20, 0, 0, DateTimeKind.Utc),
                            DestinationId = 4,
                            FlightNumber = "JG103",
                            Status = 1,
                            TotalSeats = 6
                        },
                        new
                        {
                            Id = 5,
                            AirlineId = 5,
                            ArrivalAtUtc = new DateTime(2026, 5, 12, 8, 30, 0, 0, DateTimeKind.Utc),
                            AvailableSeats = 6,
                            BasePrice = 199.00m,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            DepartureAtUtc = new DateTime(2026, 5, 12, 6, 10, 0, 0, DateTimeKind.Utc),
                            DestinationId = 5,
                            FlightNumber = "JG104",
                            Status = 1,
                            TotalSeats = 6
                        },
                        new
                        {
                            Id = 6,
                            AirlineId = 2,
                            ArrivalAtUtc = new DateTime(2026, 5, 12, 19, 20, 0, 0, DateTimeKind.Utc),
                            AvailableSeats = 6,
                            BasePrice = 139.00m,
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            DepartureAtUtc = new DateTime(2026, 5, 12, 18, 0, 0, 0, DateTimeKind.Utc),
                            DestinationId = 6,
                            FlightNumber = "JG105",
                            Status = 1,
                            TotalSeats = 6
                        });
                });

            modelBuilder.Entity("JetGo.Domain.Entities.FlightSeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId", "SeatNumber")
                        .IsUnique();

                    b.ToTable("FlightSeats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = 2,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = 3,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "1C"
                        },
                        new
                        {
                            Id = 4,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = 5,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            Id = 6,
                            FlightId = 1,
                            IsReserved = false,
                            SeatNumber = "2C"
                        },
                        new
                        {
                            Id = 7,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = 8,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = 9,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "1C"
                        },
                        new
                        {
                            Id = 10,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = 11,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            Id = 12,
                            FlightId = 2,
                            IsReserved = false,
                            SeatNumber = "2C"
                        },
                        new
                        {
                            Id = 13,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = 14,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = 15,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "1C"
                        },
                        new
                        {
                            Id = 16,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = 17,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            Id = 18,
                            FlightId = 3,
                            IsReserved = false,
                            SeatNumber = "2C"
                        },
                        new
                        {
                            Id = 19,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = 20,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = 21,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "1C"
                        },
                        new
                        {
                            Id = 22,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = 23,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            Id = 24,
                            FlightId = 4,
                            IsReserved = false,
                            SeatNumber = "2C"
                        },
                        new
                        {
                            Id = 25,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = 26,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = 27,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "1C"
                        },
                        new
                        {
                            Id = 28,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = 29,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            Id = 30,
                            FlightId = 5,
                            IsReserved = false,
                            SeatNumber = "2C"
                        },
                        new
                        {
                            Id = 31,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = 32,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = 33,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "1C"
                        },
                        new
                        {
                            Id = 34,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = 35,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            Id = 36,
                            FlightId = 6,
                            IsReserved = false,
                            SeatNumber = "2C"
                        });
                });

            modelBuilder.Entity("JetGo.Domain.Entities.NewsArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NewsArticles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Od maja 2026. godine dostupna je nova linija iz Sarajeva prema Becu sa vise termina tokom sedmice.",
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80",
                            IsPublished = true,
                            PublishedAtUtc = new DateTime(2026, 4, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "JetGo uvodi novu liniju Sarajevo - Bec"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Pripremite pasos, provjerite vrijeme polaska i dodjite na aerodrom najmanje dva sata prije medjunarodnog leta.",
                            CreatedAtUtc = new DateTime(2026, 4, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1529074963764-98f45c47344b?auto=format&fit=crop&w=1200&q=80",
                            IsPublished = true,
                            PublishedAtUtc = new DateTime(2026, 4, 22, 14, 30, 0, 0, DateTimeKind.Utc),
                            Title = "Savjeti za brzi check-in prije putovanja"
                        });
                });

            modelBuilder.Entity("JetGo.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("JetGo.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("JetGo.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("JetGo.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<string>("ReservationCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StatusChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusChangedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("ReservationCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("JetGo.Domain.Entities.ReservationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightSeatId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlightSeatId");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservationItems", (string)null);
                });

            modelBuilder.Entity("JetGo.Domain.Entities.RevokedToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("JwtId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RevokedTokens", (string)null);
                });

            modelBuilder.Entity("JetGo.Domain.Entities.SearchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("UserId");

                    b.ToTable("SearchHistories", (string)null);
                });

            modelBuilder.Entity("JetGo.Domain.Entities.SupportMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminReply")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("RepliedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SupportMessages", (string)null);
                });

            modelBuilder.Entity("JetGo.Domain.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("JetGo.Infrastructure.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("JetGo.Domain.Entities.Airport", b =>
                {
                    b.HasOne("JetGo.Domain.Entities.City", "City")
                        .WithMany("Airports")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("JetGo.Domain.Entities.City", b =>
                {
                    b.HasOne("JetGo.Domain.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("JetGo.Domain.Entities.Destination", b =>
                {
                    b.HasOne("JetGo.Domain.Entities.Airport", "ArrivalAirport")
                        .WithMany("ArrivalDestinations")
                        .HasForeignKey("ArrivalAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JetGo.Domain.Entities.Airport", "DepartureAirport")
                        .WithMany("DepartureDestinations")
                        .HasForeignKey("DepartureAirportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArrivalAirport");

                    b.Navigation("DepartureAirport");
                });

            modelBuilder.Entity("JetGo.Domain.Entities.Flight", b =>
                {
                    b.HasOne("JetGo.Domain.Entities.Airline", "Airline")
                        .WithMany("Flights")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JetGo.Domain.Entities.Destination", "Destination")
                        .WithMany("Flights")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("JetGo.Domain.Entities.FlightSeat", b =>
                {
                    b.HasOne("JetGo.Domain.Entities.Flight", "Flight")
                        .WithMany("Seats")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("JetGo.Domain.Entities.Notification", b =>
                {
                    b.HasOne("JetGo.Infrastructure.Identity.AppUser", null)
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JetGo.Domain.Entities.Payment", b =>
                {
                    b.HasOne("JetGo.Domain.Entities.Reservation", "Reservation")
                        .WithOne("Payment")
                        .HasForeignKey("JetGo.Domain.Entities.Payment", "ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("JetGo.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("JetGo.Infrastructure.Identity.AppUser", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JetGo.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("JetGo.Domain.Entities.Flight", "Flight")
                        .WithMany("Reservations")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JetGo.Infrastructure.Identity.AppUser", null)
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("JetGo.Domain.Entities.ReservationItem", b =>
                {
                    b.HasOne("JetGo.Domain.Entities.FlightSeat", "FlightSeat")
                        .WithMany()
                        .HasForeignKey("FlightSeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JetGo.Domain.Entities.Reservation", "Reservation")
                        .WithMany("Items")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightSeat");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("JetGo.Domain.Entities.RevokedToken", b =>
                {
                    b.HasOne("JetGo.Infrastructure.Identity.AppUser", null)
                        .WithMany("RevokedTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JetGo.Domain.Entities.SearchHistory", b =>
                {
                    b.HasOne("JetGo.Domain.Entities.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JetGo.Infrastructure.Identity.AppUser", null)
                        .WithMany("SearchHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("JetGo.Domain.Entities.SupportMessage", b =>
                {
                    b.HasOne("JetGo.Infrastructure.Identity.AppUser", null)
                        .WithMany("SupportMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JetGo.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("JetGo.Infrastructure.Identity.AppUser", null)
                        .WithOne("UserProfile")
                        .HasForeignKey("JetGo.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("JetGo.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("JetGo.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JetGo.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("JetGo.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JetGo.Domain.Entities.Airline", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("JetGo.Domain.Entities.Airport", b =>
                {
                    b.Navigation("ArrivalDestinations");

                    b.Navigation("DepartureDestinations");
                });

            modelBuilder.Entity("JetGo.Domain.Entities.City", b =>
                {
                    b.Navigation("Airports");
                });

            modelBuilder.Entity("JetGo.Domain.Entities.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("JetGo.Domain.Entities.Destination", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("JetGo.Domain.Entities.Flight", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("JetGo.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("JetGo.Infrastructure.Identity.AppUser", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reservations");

                    b.Navigation("RevokedTokens");

                    b.Navigation("SearchHistories");

                    b.Navigation("SupportMessages");

                    b.Navigation("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
